spring:
  datasource:
    url: jdbc:p6spy:mysql://localhost:3306/product_center?useSSL=false&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
  # note that "spring.jpa.database-platform=org.hibernate.dialect.MySQL5Dialect" was deprecated
  hibernate:
    dialect:
      storage_engine: innodb

logging:
  level:
    root: INFO